### ISSUE TITLE
Break answers up

### ISSUE THREAD

**Issue by galantra** [evolverine/covid-19-anki-deck#12]
Some questions have cumulative answers. They can easily be split up into the answer components. This would follow https://www.supermemo.com/en/archives1990-2015/articles/20rules

e. g.:

> Why is it hard to estimate the case fatality rate (CFR) for COVID-19?

> - official numbers do not reflect reality
> - no mortality data available for ongoing cases

**Comment by NakedMoleRatScientist** [comment]
That specific question is already broken into another, specifically the question asking about why the official numbers do not reflect reality, but that question is even more complex.

Looks to me that they could broken into two cloze items, though I would still keep the question alongside the cloze deletion items.

**Comment by evolverine** [comment]
thanks to both for the impetus to do it. See how I tried to solve it (in the commit attached to this ticket), and do let me know if you would change anything, and what.
