### ISSUE TITLE
Use a separate note type or tag the cards with anything like src-covid19 or src-covid19-evolverine

### ISSUE THREAD

**Issue by aleksejrs** [evolverine/covid-19-anki-deck#19]
Per issue #16. I move the cards into a more global deck.

**Comment by evolverine** [comment]
Just made it look for the 'covid-19' tag. Let me know if that solves the issue for you.

**Comment by aleksejrs** [comment]
I want to know rather if I editing the card is safe, if I can change its note type to a cloze one, although it wouldn't help if the note is deleted from the source deck.

**Comment by evolverine** [comment]
Depends on what you mean by 'safe'. You can make any changes, of course, but at the moment of updating the deck you will be prompted to convert the cards back again. I'd say you have two options for making changes:

- if you think that the changes you want to make are good quality and useful for others too, then you can make them and open a pull request (or an issue ticket) here for them to be integrated into the main deck. This way there will be no differences between your deck and the "main" one (the one in this repository)
- if you want to make changes only for your own study, I'd personally create new cards for them and leave the original ones untouched (optionally you can suspend any card from this deck that you do not wish to study). This way when you update from this deck your changes will remain untouched.
