### ISSUE TITLE
Bogus information

### ISSUE THREAD

**Issue by NakedMoleRatScientist** [evolverine/covid-19-anki-deck#22]
Apparently, [US intelligence](https://www.bloomberg.com/news/articles/2020-04-01/china-concealed-extent-of-virus-outbreak-u-s-intelligence-says) reported that china numbers may be partly bogus. We could include this in the deck as "US intelligence accused China of intentional manipulation of the numbers", without stating it as absolute facts.

We know that different countries reports coronavirus cases in different way, such as Italy reporting death if a person is shown to be infected without necessarily confirming that their death is caused or contributed to by coronavirus.

Anyway, what's your all thought on this and should this be included?

**Comment by evolverine** [comment]
I think a reasonable degree of scepticism regarding official government data (and I'm not excluding the US or other governments here) is warranted, and thank you for the link. I've added a couple more questions about these issues (continuing the context of "Official numbers not reflecting the ongoing reality of the COVID-19 spread"), see if they make sense to you, or if you'd make any changes.
