### ISSUE TITLE
git repository not found at URL evolverine/covid-19-anki-deck

### ISSUE THREAD

**Issue by galantra** [evolverine/covid-19-anki-deck#27]
I got this error when trying to import from github:

![grafik](https://user-images.githubusercontent.com/52420923/83405878-c5e6f880-a40d-11ea-953c-b04276e29c78.png)

**Comment by evolverine** [comment]
Yes, with the recent CrowdAnki update one has to use the full URL, as such: https://github.com/evolverine/covid-19-anki-deck/

**Comment by galantra** [comment]
Thanks for the info.

Now it has worked with `evolverine/covid-19-anki-deck/` – maybe CrowdAnki has reverted the update mentioned above; maybe it's because I'm still on Anki 2.1.22.

Anyway, I've been able to update the deck.

**Comment by evolverine** [comment]
interesting and unexpected, thanks for reporting. I have a sense that that feature was temporarily taken out because maybe it had some issues.
