### ISSUE TITLE
Explain why you needed to introduce a code of conduct

### ISSUE THREAD

**Issue by aleksejrs** [evolverine/covid-19-anki-deck#28]
It's not like you are in the USA.

Eventually you might yourself become a target of a self-designed CoC's enforcer (probably irrelevant since you introducted the CoC in March: _e.g._, you have a "master" branch in your repo).

(Probably irrelevant since you introducted the CoC in March: ) Are you going to eventually refuse to cite sources that use the word "blacklist"?

I think I am not against what it is written in it, but what codes of conduct are misused for eventually. Also, the code may be larger than the project itself.

And whose is that @opayq.com e-mail address?

**Comment by evolverine** [comment]
The email address is mine. I did not "need" to introduce a code of conduct; it's one of the recommended ways of helping to create a well functioning virtual community. And this particular one is a template I found (that I later saw was suggested by github too) that feels useful, and that it lays out a series of guidelines that I could get behind.

**Comment by evolverine** [comment]
I don't know what you mean by being in the USA or not, or about using the word "blacklist".

**Comment by aleksejrs** [comment]
I e-mailed you a few days ago.

**Comment by evolverine** [comment]
Yes, just got the chance to respond. From my email I'll mention this here:

> I also worked within the ASF for a while, where they mostly do try to implement their "community over code" policy, with which I very much agree with. I see no reason to think that a code of conduct will at all hinder the creation of a welcoming community. I have also seen communities having to go through conflict before adopting such guidelines, and I don't think it's necessary to wait for that to happen to do it. Plus, I'd guess it's overall more inviting for new members to have it than not.

**Comment by aleksejrs** [comment]
Well, I hope that, if anything happens, code of conduct will be enforced by those who have already cared about the community inside the project, not those who arrived only to enforce it from outside.
